const fakeData = [
    {
        name: 'Robert Patrik',
        id: 'pt01',
        age: 34,
        profession: 'Journalist',
        fee: 9000,
        img: 'https://www.freepik.com/free-photo/confident-european-businessman-smiling-closeup-portrait-jobs-career-campaign_17604100.htm',
    },
    {
        name: 'Peter Jonshon',
        id: 'pt02',
        age: 42,
        profession: 'Businessman',
        fee: 9000,
        img: 'https://www.freepik.com/free-photo/waist-up-shot-handsome-self-confident-cheerful-male-entrepreneur-has-broad-smile_10749454.htm',
    },
    {
        name: 'Anthonio Sam',
        id: 'pt03',
        age: 31,
        profession: 'Artist',
        fee: 9000,
        img: 'https://www.freepik.com/free-photo/portrait-cheerful-bearded-african-american-man-has-happy-expression-smiles-broadly-has-white-perfect-teeth_14035833.htm',
    },
    {
        name: 'Luis Verdan',
        id: 'pt04',
        age: 26,
        profession: 'Student',
        fee: 7000,
        img: 'https://www.freepik.com/free-photo/red-haired-serious-young-man-blogger-looks-confidently_10521308.htm',
    },
    {
        name: 'Pavel Paulo',
        id: 'pt05',
        age: 29,
        profession: 'Teacher',
        fee: 8000,
        img: 'https://www.freepik.com/free-photo/waist-up-portrait-handsome-serious-unshaven-male-keeps-hands-together-dressed-dark-blue-shirt-has-talk-with-interlocutor-stands-against-white-wall-self-confident-man-freelancer_10421502.htm',
    },
    {
        name: 'Navin Pan',
        id: 'pt06',
        age: 25,
        profession: 'Student',
        fee: 7000,
        img: 'https://www.freepik.com/free-photo/cheerful-indian-businessman-smiling-closeup-portrait-jobs-career-campaign_17830490.htm',
    },
    {
        name: 'Martin Luthar',
        id: 'pt07',
        age: 52,
        profession: 'Professor',
        fee: 9000,
        img: 'https://www.freepik.com/free-photo/senior-man-white-sweater-eyeglasses_13557689.htm',
    },
    {
        name: 'Lathio Samuel',
        id: 'pt08',
        age: 32,
        profession: 'Teacher',
        fee: 8000,
        img: 'https://www.freepik.com/free-photo/handsome-confident-smiling-man-with-hands-crossed-chest_9583860.htm',
    },
    {
        name: 'Jhon Fedrik',
        id: 'pt09',
        age: 46,
        profession: 'Fashion Designer',
        fee: 9000,
        img: 'https://www.freepik.com/free-photo/yeah-feeling-courage-readiness-achieve-success-confident-delighted-optimistic-african-american-bearded-man-raising-clenched-fists-celebration-triumphing-being-happy-with-good-result_17612619.htm#query=portrait++man++men&position=17',
    },
]